Repository gardener/ops-toolbelt, pull requests merged in 2022-07, with the labels that each got.

#78 Add sysstat package (e.g. for iostat commands)
  dockerfile-configs/common-components.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#82 Include `nerdctl` default configs to make it easy to consume
  dockerfile-configs/common-components.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#80 Add iotop and iftop utilities
  dockerfile-configs/common-components.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#79 Allow scheduling ops-pod on any node by default
  hacks/ops-pod
Labels: reviewed/lgtm, size/xs

#83 Use Ubuntu:22.04 base image and update dependencies
  .ci/build
  README.md
  dockerfile-configs/common-components.yaml
  dotfiles/.install_on_demand/.table
  dotfiles/.install_on_demand/.wireguard
Labels: needs/ok-to-test, reviewed/lgtm, size/s
