Repository gardener/ops-toolbelt, pull requests merged in 2022-05, with the labels that each got.

#68 Fix build - Use corresponding script for python 3.6
  dockerfile-configs/common-components.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#67 Completion for k alias
  dotfiles/.bash_aliases
Labels: needs/ok-to-test, size/xs

#65 Enhance the ops-pod Pod spec
  hacks/ops-pod
Labels: kind/enhancement, needs/ok-to-test, size/xs

#69 Update version of IaaS clients
  .ci/build
  dockerfile-configs/aliyun-components.yaml
  dockerfile-configs/aws-components.yaml
  dockerfile-configs/az-components.yaml
  dockerfile-configs/gcp-components.yaml
  dockerfile-configs/iaas-components.yaml
  dockerfile-configs/openstack-components.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#71 Fix gcloud and azure-cli installations
  dockerfile-configs/az-components.yaml
  dockerfile-configs/common-components.yaml
  dockerfile-configs/gcp-components.yaml
  dockerfile-configs/iaas-components.yaml
  generator/lib/commands.py
  generator/lib/components.py
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#72 Update k8s versions
  .ci/k8s_versions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#70 Remove dependency towards deprecated gardenctl-v1
  .ci/build
  .ci/build_pipeline_definitions
  .ci/component_descriptor
  .ci/pipeline_definitions
  .ci/set_dependency_version
  .ci/test
  GARDENCTL_VERSION
  README.md
  dockerfile-configs/gardenctl-components.yaml
  dockerfile-configs/iaas-components.yaml
Labels: needs/ok-to-test, needs/rebase, needs/review, size/m

#74 Fixes ghelp command when there are pinned versions of tools
  dockerfile-configs/openstack-components.yaml
  generator/lib/commands.py
  hacks/ghelp
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#75 Drop Image Matrix (iaas CLIs x kubectl versions)
  .ci/build
  .ci/build_pipeline_definitions
  .ci/iaas_providers
  .ci/k8s_versions
  .ci/pipeline_definitions
  .ci/test
  README.md
  dockerfile-configs/aliyun-components.yaml
  dockerfile-configs/aws-components.yaml
  dockerfile-configs/az-components.yaml
  dockerfile-configs/common-components.yaml
  dockerfile-configs/gcp-components.yaml
  dockerfile-configs/openstack-components.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/l
