Repository gardener/ops-toolbelt, pull requests merged in 2023-11, with the labels that each got.

#95 fix default image
  README.md
  hacks/ops-pod
Labels: needs/ok-to-test, needs/changes, needs/review, size/xs

#96 Add script to install `etcdctl` on demand
  dockerfile-configs/common-components.yaml
  generator/lib/commands.py
  hacks/install_etcdctl
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#97 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  README.md
  hacks/ops-pod
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
