Repository gardener/ops-toolbelt, pull requests merged in 2024-04, with the labels that each got.

#113 Build multi-arch OCI image
  .ci/pipeline_definitions
  .gitignore
  dockerfile-configs/common-components.yaml
  generator/lib/dockerfile.py
  generator/validate-tools.py
  hacks/install_etcdctl
  hacks/install_k9s
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#114 Publish releases to Google Artifact Registry
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#116 `etcdctl` precalculated argument values are validated before preset.
  install_on_demand/.etcdctl
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#100 Added a cheatsheet to help operators when using the etcdctl tool
  dockerfile-configs/common-components.yaml
  hacks/print-etcd-cheatsheet
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#119 Fixes the path for cacert used in etcdctl.
  hacks/print-etcd-cheatsheet
  install_on_demand/.etcdctl
Labels: needs/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/s
