Repository gardener/ops-toolbelt, pull requests merged in 2024-11, with the labels that each got.

#140 Update etcdctl CA and TLS cert paths to support etcd-druid:v0.23.0
  install_on_demand/.etcdctl
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#154 Updates etcd version to install etcdctl.
  hacks/install_etcdctl
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#158 Fixing linter installations
  .ci/verify-bandit
  .ci/verify-shellcheck
  Makefile
Labels: needs/ok-to-test, reviewed/lgtm, size/s
